image: maven:latest

stage:
    - build
    - test
    -package
    deploy

build_job:
  stage: build
  tags:
    - docker
  
  script:
    - echo "maven complie started"
    - "mvn complie"

test_job:
  stage: test
  tags:
    -docker

script:
  - echo "maven is started"
  - "mvn test"

package_job:
  stage: package
  tags:
    - docker
  
  script:
  - echo "maven packaging started"
  - "maven package"

deploy_job:
  stage: deploy
  tags:
    -docker 
  
  script:
    - echo "maven deploy started"
